title: Singapore Customs
url: https://customs.gov.sg
favicon: /images/favicon.png

# Site colors
colors:
  primary-color: '#20639b'
  secondary-color: '#041D42'
  media-colors:
    - title: media-color-one
      color: '#A2AAAD'
    - title: media-color-two
      color: '#20639B'
    - title: media-color-three
      color: '#990000'
    - title: media-color-four
      color: '#5B6B79'
    - title: media-color-five
      color: '#041D42'

resources_name: news-and-media

collections:
  about-us:
    output: true
  organisation-overview:
    output: true
  individuals:
    output: true
  businesses:
    output: true
  news-and-media:
    output: true
  eservices:
    output: true
  individuals_going-through-customs:
    output: true
  registration-services:
    output: true
  business-resources:
   output: true
  importing-goods-more: 
    output: true
  transhipment-procedures: 
    output: true
  transhipment-procedures-requirements:
    output: true
  chemical-weapons-convention: 
    output: true
  CWC-inspections: 
    output: true
  CWC-licensing-requirements: 
    output: true
  strategic-goods-permit-and-reg-req: 
    output: true
  strategic-goods-control: 
    output: true
  iras-scheme: 
    output: true
  establishing-customs-value-for-imports: 
    output: true
  import-procedures-req: 
    output: true
  importing-by-post-or-courier-service:
    output: true
  temporary-import-scheme:
    output: true
  importing-dutiable-motor-vehicles:
    output: true
  importing-dutiable-motor-vehicles-steps:
    output: true
  importing-goods-for-destruction-or-recycling:
    output: true
  export-procedures-requirements:
    output: true
  authorised-piers-places: 
    output: true
  united-nations-security-council-sanctions: 
    output: true
  strategic-goods-control-list:
    output: true
  import-certificate-and-delivery-verification:
    output: true
  test_hidden:
    output: true
  tradenet:
    output: true 
  export-procedures-more:
    output: true   
  registration-security-lodgement:
    output: true    
  apply-update-renew-terminate-declarant-agent:
    output: true   
  import-permit-req-IPMs:   
    output: true 
  competent-authorities-requirements:   
    output: true   
  inSYNC:   
    output: true  
  certificates-of-origin:
    output: true
  ACTS:
    output: true  

google_analytics: UA-70503404-1
##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test

